### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by majones713** [buger/goreplay#474]
OS: WIN7
COMMIT: Latest commit 5aa1696

Steps To Reproduce:

1. Made a runnable jar from middleware code provided by goreplay here: 

[https://github.com/buger/goreplay/blob/master/examples/middleware/echo.java](url)

2. Created windows .bat file  (i.e. C:\goreplay-concerto-middleware-jar\middleware.bat) which included this command inside:

`java -jar "C:\goreplay-concerto-middleware-jar\middleware.jar"`

3. Executed the following command:

`C:\Users\206435745\go\src\github.com\buger\gor>gor --input-raw :8000 --middleware "C:\goreplay-concerto-middleware-jar\middleware.bat" --output-stdout --input-raw-track-response --prettify-http`

4. When executed I got the below error:

`C:\Users\206435745\go\src\github.com\buger\gor>gor --input-raw :8000 --middlewar
e "C:\goreplay-concerto-middleware-jar\middleware.bat" --output-stdout --input-r
aw-track-response --prettify-http
Version:
Failed to decode input payload encoding/hex: odd length hex string 2
Failed to decode input payload encoding/hex: odd length hex string 112
panic: runtime error: index out of range

goroutine 38 [running]:
main.CopyMulty(0xa433d0, 0x21014090, 0x20fd66c0, 0x1, 0x1, 0x0, 0x0)
        C:/Users/206435745/go/src/github.com/buger/gor/emitter.go:64 +0xd14
created by main.Start
        C:/Users/206435745/go/src/github.com/buger/gor/emitter.go:25 +0x321`

**Comment by frankfarmer** [comment]
I'm seeing a similar panic in the binary release of 0.16.1

```
PANIC: pkg: runtime error: slice bounds out of range goroutine 376 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
 /usr/local/go/src/runtime/debug/stack.go:24 +0x80
main.(*HTTPClient).Send.func1(0xc823997c78, 0xc823997c90)
 /go/src/github.com/buger/goreplay/http_client.go:147 +0x52d
panic(0xa58cc0, 0xc82000e030)
 /usr/local/go/src/runtime/panic.go:443 +0x4e9
main.(*HTTPClient).Send(0xc822324a00, 0xc8212e183f, 0xb00, 0xb00, 0x0, 0x0, 0x0, 0x0, 0x0)
 /go/src/github.com/buger/goreplay/http_client.go:303 +0x20c6
main.(*HTTPOutput).sendRequest(0xc821304000, 0xc822324a00, 0xc8212e1800, 0xb3f, 0xb3f)
 /go/src/github.com/buger/goreplay/output_http.go:205 +0x2b6
main.(*HTTPOutput).start
```

**Comment by nirmitsrivastava** [comment]
Do we know what was the problem here ? @buger @frankfarmer @majones713
