### ISSUE TITLE
 PANIC: pkg: runtime error: slice bounds out of range Addr

### ISSUE THREAD

**Issue by nlmunro** [buger/goreplay#512]
This only happens on one of our frontends, but it consistently fails after a few minutes - seems to be getting some packet it doesn't like... any idea what it might be?

Command: 
gor.exe --input-raw :80 --input-raw-track-response --output-tcp ...

2017/09/06 18:49:56 PANIC: pkg: runtime error: slice bounds out of range Addr:
??_
Source port: 80
Dest port:53532
Sequence:480408639
Acknowledgment:-1775506239
Header len:5
FIN:false
Data size:106
Data:5f
G???^??}??????]f??GGw?>?]?w??????~????;??|??j????/???▲}??/????U???§????o???
  ??R)?~^?►
0

 goroutine 51 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        C:/Go/src/runtime/debug/stack.go:24 +0x80
github.com/buger/gor/raw_socket_listener.(*Listener).processTCPPacket.func1(0x22
4a85a0)
        C:/work/src/github.com/buger/gor/raw_socket_listener/listener.go:676 +0x
5c
panic(0x81fda0, 0x2026e010)
        C:/Go/src/runtime/panic.go:458 +0x40b
github.com/buger/gor/proto.ParseHeaders(0x21925200, 0x77, 0x77, 0x20279c08)
        C:/work/src/github.com/buger/gor/proto/proto.go:233 +0x596
github.com/buger/gor/raw_socket_listener.(*TCPMessage).updateBodyType(0x20684a80
)
        C:/work/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:376
+0xc8
github.com/buger/gor/raw_socket_listener.(*TCPMessage).AddPacket(0x20684a80, 0x2
24a85a0)
        C:/work/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:149
+0x448
github.com/buger/gor/raw_socket_listener.(*Listener).processTCPPacket(0x2034c6c0
, 0x224a85a0)
        C:/work/src/github.com/buger/gor/raw_socket_listener/listener.go:743 +0x
14dd
github.com/buger/gor/raw_socket_listener.(*Listener).listen(0x2034c6c0)
        C:/work/src/github.com/buger/gor/raw_socket_listener/listener.go:148 +0x
19c
created by github.com/buger/gor/raw_socket_listener.NewListener
        C:/work/src/github.com/buger/gor/raw_socket_listener/listener.go:119 +0x
33a

**Comment by buger** [comment]
Looks like a Chunked encoding issue. Any chance you can give me tcpdump which replicate request?

**Comment by nlmunro** [comment]
I've installed WinDump (tcpdump compatible version for Windows) - are there any particular flags I should use? I'm not familiar with using this...
