### ISSUE TITLE
paniced when replay

### ISSUE THREAD

**Issue by arsane** [buger/goreplay#528]
2017/11/01 08:29:11 [HTTPClient] Response:  
2017/11/01 08:29:11 PANIC: pkg: runtime error: index out of range goroutine 237 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
main.(*HTTPClient).Send.func1(0xc8223efc78, 0xc8223efc90)
	/go/src/github.com/buger/goreplay/http_client.go:147 +0x52d
panic(0xa58cc0, 0xc82000e0c0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/buger/goreplay/proto.headerIndex(0xc8213dc000, 0x54a, 0x19000, 0xc8223ef810, 0x11, 0x11, 0x1)
	/go/src/github.com/buger/goreplay/proto/proto.go:95 +0x24e
github.com/buger/goreplay/proto.header(0xc8213dc000, 0x54a, 0x19000, 0xc8223ef810, 0x11, 0x11, 0x0, 0x0, 0x0, 0x11, ...)
	/go/src/github.com/buger/goreplay/proto/proto.go:127 +0x9a
github.com/buger/goreplay/proto.Header(0xc8213dc000, 0x54a, 0x19000, 0xc8223ef810, 0x11, 0x11, 0x0, 0x0, 0x0)
	/go/src/github.com/buger/goreplay/proto/proto.go:292 +0x7d
main.(*HTTPClient).Send(0xc82154c080, 0xc8214d65bf, 0x245, 0x245, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/buger/goreplay/http_client.go:206 +0xd29
main.(*HTTPOutput).sendRequest(0xc8215c45a0, 0xc82154c080, 0xc8214d6580, 0x284, 0x284)
	/go/src/github.com/buger/goreplay/output_http.go:205 +0x2b6
main.(*HTTPOutput).startWorker(0xc8215c45a0)
	/go/src/github.com/buger/goreplay/output_http.go:125 +0x1c7
created by main.(*HTTPOutput).workerMaster
	/go/src/github.com/buger/goreplay/output_http.go:99 +0x85

**Comment by arsane** [comment]
with `0.16.1` release.
