### ISSUE TITLE
v0.16.1   PANIC: pkg: runtime error: slice bounds out of range goroutine

### ISSUE THREAD

**Issue by monotone** [buger/goreplay#541]
Hi,  I known it seems you have fix this issue after v0.15.*。

But  I got this error today when use **v0.16.1** really.

```
2017/12/20 20:54:24 [HTTPClient] Response:
2017/12/20 20:54:24 PANIC: pkg: runtime error: slice bounds out of range goroutine 298 [running]:
runtime/debug.Stack(0xc425637650, 0x2, 0x2)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/debug/stack.go:24 +0xa7
main.(*HTTPClient).Send.func1(0xc425637d10, 0xc425637d28)
	/private/tmp/gor-20170919-17638-1u46ea3/src/github.com/buger/goreplay/http_client.go:147 +0x351
panic(0x4485780, 0x4808de0)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
main.(*HTTPClient).Send(0xc4240da880, 0xc420050cff, 0x77, 0x77, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/gor-20170919-17638-1u46ea3/src/github.com/buger/goreplay/http_client.go:304 +0x1eb7
main.(*HTTPOutput).sendRequest(0xc42123e000, 0xc4240da880, 0xc420050cc0, 0xb6, 0xb6)
	/private/tmp/gor-20170919-17638-1u46ea3/src/github.com/buger/goreplay/output_http.go:205 +0x19a
main.(*HTTPOutput).startWorker(0xc42123e000)
	/private/tmp/gor-20170919-17638-1u46ea3/src/github.com/buger/goreplay/output_http.go:125 +0x246
created by main.(*HTTPOutput).workerMaster
	/private/tmp/gor-20170919-17638-1u46ea3/src/github.com/buger/goreplay/output_http.go:99 +0x4a
```

I think this will help you to fix this.

**Comment by jhmartin** [comment]
Seeing this as well:

`goreplay -input-raw :80 -output-http DESTSERVER -output-http-workers 1` works, 
`goreplay -input-raw :80 -output-http DESTSERVER` fails:
```2018/10/16 11:03:06 [HTTPClient] Response:
2018/10/16 11:03:06 PANIC: pkg: runtime error: slice bounds out of range goroutine 118 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
main.(*HTTPClient).Send.func1(0xc821d8fc78, 0xc821d8fc90)
	/go/src/github.com/buger/goreplay/http_client.go:147 +0x52d
panic(0xa58cc0, 0xc8200100c0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/buger/goreplay/proto.Path(0xc822098000, 0x4, 0x19000, 0x0, 0x0, 0x0)
	/go/src/github.com/buger/goreplay/proto/proto.go:353 +0x1b6
github.com/buger/goreplay/proto.Status(0xc822098000, 0x4, 0x19000, 0x0, 0x0, 0x0)
	/go/src/github.com/buger/goreplay/proto/proto.go:453 +0x46
main.(*HTTPClient).Send(0xc8211a6900, 0xc8221ce100, 0x8be, 0xb00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/buger/goreplay/http_client.go:209 +0x274c
main.(*HTTPOutput).sendRequest(0xc8200865a0, 0xc8211a6900, 0xc82221f200, 0x8df, 0x8df)
	/go/src/github.com/buger/goreplay/output_http.go:205 +0x2b6
main.(*HTTPOutput).startWorker(0xc8200865a0)
	/go/src/github.com/buger/goreplay/output_http.go:125 +0x1c7
created by main.(*HTTPOutput).workerMaster
	/go/src/github.com/buger/goreplay/output_http.go:99 +0x85
```

**Comment by jhmartin** [comment]
Seeing this error as well, though the errors occur with or without the workers limit.

**Comment by loop-evgeny** [comment]
Also getting this error in the same place (`http_client.go:304`) with v0.16.1.

My command line:
```
sudo ./goreplay --input-raw :80 --output-http "http://TARGET_HOSTNAME:81" --http-original-host --http-disallow-header "User-Agent: Pingdom.*" --exit-after 30s
```
