### ISSUE TITLE
Can support GRPC？

### ISSUE THREAD

**Issue by hyhlinux** [buger/goreplay#544]

**Comment by grantkl** [comment]
👍 

This is the exception we get with gRPC:
`2017-11-13 21:44:37.717 level=ERROR thread=grpc-default-worker-ELG-3-3 logger=NettyServerTransport messageId= message="Transport failed"
 
io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 000000040100000000000077012400000003000000000f41
                at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
                at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:288)
                at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:221)
                at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:413)
                at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
                at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
                at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
                at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
                at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
                at java.lang.Thread.run(Thread.java:748)
 `

I think it may be related to OpenSSL but I haven't dug enough.

**Comment by grantkl** [comment]
May or may not be related: https://stackoverflow.com/questions/45571314/connection-error-io-netty-handler-codec-http2-http2exception-http-2-client-pref
