### ISSUE TITLE
runtime panic inside a docker container

### ISSUE THREAD

**Issue by sandys** [buger/goreplay#545]
hi,
I'm running goreplay inside a debian docker container.

This is my command - `./goreplay --input-raw :80 --input-raw :443   --input-raw :9001 --output-stdout --verbose --http-set-header 'User-Agent: Gor' --http-allow-header "Host: api-v3.something.com"  --http-set-header 'User-Agent: Gor' --output-http https://apicherry-ledger.something.com `

this is the output.

```
2018/01/05 09:58:19 [HTTPClient] Response:  
2018/01/05 09:58:19 PANIC: pkg: runtime error: invalid memory address or nil pointer dereference goroutine 71 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x80
main.(*HTTPClient).Send.func1(0xc822ed5c68, 0xc822ed5c80)
        /go/src/github.com/buger/goreplay/http_client.go:147 +0x52d
panic(0xa58cc0, 0xc8200100a0)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
crypto/tls.(*Conn).writeRecord(0xc822ff0300, 0xc822eac316, 0xc822eac3c0, 0x98, 0x98, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:769 +0x542
crypto/tls.(*Conn).clientHandshake(0xc822ff0300, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/handshake_client.go:147 +0xfba
crypto/tls.(*Conn).Handshake(0xc822ff0300, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1033 +0xec
main.(*HTTPClient).Connect(0xc822e84780, 0x7fc3bc425100, 0xc822e7e5f0)
        /go/src/github.com/buger/goreplay/http_client.go:98 +0x38a
main.(*HTTPClient).Send(0xc822e84780, 0xc822e0953f, 0x2eb, 0x2eb, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/buger/goreplay/http_client.go:154 +0x32b5
main.(*HTTPOutput).sendRequest(0xc820098730, 0xc822e84780, 0xc822e09500, 0x32a, 0x32a)
        /go/src/github.com/buger/goreplay/output_http.go:205 +0x2b6
main.(*HTTPOutput).startWorker(0xc820098730)
        /go/src/github.com/buger/goreplay/output_http.go:125 +0x1c7
created by main.(*HTTPOutput).workerMaster
        /go/src/github.com/buger/goreplay/output_http.go:99 +0x85
```

this container runs python flask (running on port 9001)

**Comment by sandys** [comment]
just checked - this is acually working with 0.16.0 , but not with 0.16.1

**Comment by slimus** [comment]
Hi @sandys. I think it was a bug. We didn't check errors after creating output_http client. For example: 
[here](https://github.com/buger/goreplay/blob/v0.16.0/http_client.go#L96) we didn't check c.conn is null and got panic. 
Please check v1.0.0 or master branch and if you have any questions or issues feel free to create new one!
