### ISSUE TITLE
HTTPS PANIC: pkg: runtime error: invalid memory address or nil pointer dereference goroutine

### ISSUE THREAD

**Issue by nderzhak** [buger/goreplay#558]
When output endpoint is https, we get panic.

/goreplay-0.16.1 --input-file '/data/4hours_requests.gor|4800%' --output-http=https://.... --stats --output-http-stats

```
2018/03/07 00:09:15 [HTTPClient] Response:  
2018/03/07 00:09:15 PANIC: pkg: runtime error: invalid memory address or nil pointer dereference goroutine 20941 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x80
main.(*HTTPClient).Send.func1(0xc826bcfc68, 0xc826bcfc80)
        /go/src/github.com/buger/goreplay/http_client.go:147 +0x52d
panic(0xa58cc0, 0xc82000e120)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
```

**Comment by nderzhak** [comment]
DEV-1519933407 has not affected. So probably fixed already ?

**Comment by nderzhak** [comment]
No. I am actually get the same panics, minutes later.

**Comment by IuryAlves** [comment]
I am having the same problem with version `0.16.0`

**Comment by buger** [comment]
@IuryAlves try these binaries
[gor_DEV-1519933407_x64.tar.gz](https://github.com/buger/goreplay/files/1853076/gor_DEV-1519933407_x64.tar.gz)
[gor_DEV-1519933432_mac.tar.gz](https://github.com/buger/goreplay/files/1853077/gor_DEV-1519933432_mac.tar.gz)

**Comment by blieberman** [comment]
Likewise with 0.16.1.

**Comment by mtrienis** [comment]
I'm not sure if this is going to be helpful for anyone, but I noticed that once I used the actual DNS name instead of a DNS alias (e.g. CNAME), I no longer get these errors.

**Comment by buger** [comment]
@nderzhak unfortunately this stacktrace does not tell too much, you need post full output. 

Thank you.

**Comment by slimus** [comment]
Can someone to try latest master or v1.0.0? @nikolai-derzhak-distillery @IuryAlves
