### ISSUE TITLE
when used --input-file, panic: runtime error: index out of range

### ISSUE THREAD

**Issue by satishmane** [buger/goreplay#563]
So far nothing works out of box. I created sample 1.log with few lines in it and tried to read as below, but getting end of file. 

goreplay --input-file "1.log|100%" --output-stdout
Version: 
2018/03/23 05:16:45 FileInput: end of file '1.log'

**Comment by satishmane** [comment]
I then created file using goreplay and tried to replay from it. Then I am getting index of out range error

goreplay --input-file "/home/ubuntu/req_0.log|200%" --output-file 2.log

panic: runtime error: index out of range

goroutine 1 [running]:
panic(0xa58cc0, 0xc820010070)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
main.(*fileInputReader).parseNext(0xc82119d620, 0x0, 0x0)
	/go/src/github.com/buger/goreplay/input_file.go:49 +0x3ef
main.NewFileInputReader(0x7ffcfff8585a, 0x21, 0x1)
	/go/src/github.com/buger/goreplay/input_file.go:94 +0x43e
main.(*FileInput).init(0xc82000a4b0, 0x0, 0x0)
	/go/src/github.com/buger/goreplay/input_file.go:153 +0x70b
main.NewFileInput(0x7ffcfff8585a, 0x21, 0x0, 0xc82000a4b0)
	/go/src/github.com/buger/goreplay/input_file.go:119 +0xe7
reflect.Value.call(0x9fd1a0, 0xc68698, 0x13, 0xb2e318, 0x4, 0xc82119d530, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x9fd1a0, 0xc68698, 0x13, 0xc82119d530, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
main.registerPlugin(0x9fd1a0, 0xc68698, 0xc820699c90, 0x2, 0x2)
	/go/src/github.com/buger/goreplay/plugins.go:56 +0x396
main.InitPlugins()
	/go/src/github.com/buger/goreplay/plugins.go:121 +0xd51
main.main()
	/go/src/github.com/buger/goreplay/gor.go:63 +0xde3

**Comment by satishmane** [comment]
Fixed bug in my local repo to resolve "panic: runtime error: index out of range". Will push fix soon
