### ISSUE TITLE
input file rate control per second

### ISSUE THREAD

**Issue by satishmane** [buger/goreplay#564]
Hi,

Since rate control is not supported for kafka source, I have stored kafka steaming data into a file for last 24 hours.

Now I want to play from this file using percentage limiter. The file contain 1 million records and I want to stream 10 records per second, 20 records per second and so on for controlled load testing using goreplay input file.

But when I use input-file, looks like it plays entire file data as 100% rate is original speed. I tried to give less than 100% or in fact 1% to control rate. But no luck.

Can you please suggest way forward if possible using input-file to achieve control rate per second

thanks

**Comment by satishmane** [comment]
@jacek-wojciechowski-dell  thanks for your reply.

1. Can you please elaborate about re-writing timestamps in goreplay file? Does this mean, I need to add timestamp or modify timestamp to increase gap between set of payload records in my saved data file .e.g. 10 records at different time interval in save fole. And then goreplay will play by looking at timestamps. I did not understand how goreplay will know which attribute to look at payload. Can you please help me understand.

2. 1000% flow control? My processing engine currently handles 20 records per second at normal streaming rate using kafka. Now in order to test my engine, I want to write to Kafka queue using goreplay by reading records at controlled rate from input file. 

I tested like goreplay as below to test controlled rate first before playing data on my kafka queue.

goreplay --input-file "payload.log|0.0001%" --output-file="test.log" --output-file-append

I did tail on test.log to see how many records are written per second. What happens, when I execute above goreplay command, I see entire file on tail. I gave 0.0001% of total number of records in file to slow down input control rate. But no luck

Can you please share input on 1 & 2 points

thanls

**Comment by jacek-wojciechowski-dell** [comment]
@satishmane 
Reg. 1: Goreplay replays by looking at timestamps - you can manipulate the timestamps to achieve the replay rate that you need
Reg. 2: I thought you wanted to increase the rate of replaying but you were giving examples with less than 100% (which means slowing the replaying down) instead of more than 100% (if you want to speed the replaying up) - hence my suggestion (but don't take 1000% literally, I meant "larger than 100%" for increasing replay speed)

Moreover, I wouldn't be testing this with just '--input-file' option as it might lead to misleading results. Rather test with capturing traffic from the network.

**Comment by satishmane** [comment]
@jacek-wojciechowski-dell 
Reg 1: You mean to say timestamp is added by goreplay when it writes to file using --output-file. If yes, then in  my case, goreplay writes json payload as is received from my kafka source to output file with smiley faces delimiter. There is no timestamp appended to each playload. I can add timestamp if there is format info.

I checked by writing http traffic to output file. And I see line after each delimter. Is highlighted string starting with 1521 is time added by goreplay? Can you please share small example of payload about timestamp. I can then add/manipulate similiar timestamp to my output file.

🐵🙈🙉
1 425dae6e63e76928c1b3f887236117e711c88c08 **1521824057127879000**

Again thanks for your quick response. I really appreciate your contribution.

**Comment by buger** [comment]
Hello! :)

Can you post exactly the same command you use for replaying your log?

So, just to clarify, at the moment you can't control replay speed using --input-file, I am right?

**Comment by buger** [comment]
Logic itself here is really quite simple 

https://github.com/buger/goreplay/blob/a65256d70731b58ba5c42d1f3a5c2f13c6416409/input_file.go#L209-L216

Where speedFactor is set from here:

https://github.com/buger/goreplay/blob/master/limiter.go#L42-L45

So if you set 100%, it basically means replay on the same speed. If 1000% - 10x speed.

**Comment by satishmane** [comment]
@buger 
Hi,
Here are the steps.

1. I want to stream traffic from our production kafka cluster to testing kafka cluster to do performance load testing. The traffic in production is 10 records per second. And I want to control this traffic by increasing no of records per second e.g 20 per second, 30 per second etc. 

2. Since goreplay does not support rate limiting for Kafka, I saved kafka input stream into file as below to create one large file

**goreplay --input-kafka-host 'ipaddr:9092,' --input-kafka-topic 'data' --output-file=devicedata.log --output-file-append**

The devicedata.log contains json records delimited by 🐵🙈🙉

Please note that there is no timestamp or anything added by goreplay in this file. file looks like this
{"acc":"445","id":"6","md":"ft","cid":"trs","tmud":"6767-ghh","ctype":"application/json","content":{"mid":"6767","mtype":"1","stype":"1","msgtype":"2","seqNo":21080,"utm
":1521833361,"tmfx":1521833361,"lat":9.5961,"lng":106.8297576,"alt":0}}
🐵🙈🙉
{"acc":"645","id":"654","md":"ft","cid":"trs","tmud":"6767-fgf","ctype":"application/json","content":{"mid":"676","mtype":"1","stype":"0","msgtype":"2","seqNo":15543,"utm
":1521833361,"tmfx":1521833361,"lat":4.2817431,"lng":-88.041172,"alt":0}}
🐵🙈🙉

3. Now I want to play records from above file by setting limiter e.g. 5% or 100% whatever that value could be to achieve speed of 10 records per second or 20 seconds per second.
Here is commnd to replay saved traffic from file. Just to test, I replayed it to another file.

**goreplay --input-file "payload.log|1%" --output-file="test.log" --output-file-append**

The payload.log contains around 1 million json records. I did tail on test.log and monitored rate. I do not see rate controlled as per given percentage. I see complete of file on tail. I tried reducing rate by setting 0.1% or 1% which means lower the percentage, it should long time to replay entire file.

Now I guess, problem may be because of timestamp difference you all refering to. **From where does goreply gets timestamp of each reocord from input file to get difference between previous and current record? There is no timestamp tagged by goreplay while creating input file. Am I missing anything here?**

**Comment by satishmane** [comment]
@buger 
Just to verify timestamp

1. I did sample test as below. I compiled goreplay by adding print statements to print current timestamp and lastTime.

2. created output file for http traffic 
goreplay --input-raw :8080 --output-file="test.log" 

3. Now replayed file just to see current timestamp and lastTime value
goreplay --input-file="test.log"  --output-std

it printed below entries. Can not make out what is going on here. From where it is reading timestamp? because it does not input file.
2018/03/25 11:53:06 current time:1 latesttime:1

**Comment by buger** [comment]
First of all, try these latest binaries:
[gor_DEV-1519933432_mac.tar.gz](https://github.com/buger/goreplay/files/1845419/gor_DEV-1519933432_mac.tar.gz)
[gor_DEV-1519933407_x64.tar.gz](https://github.com/buger/goreplay/files/1845418/gor_DEV-1519933407_x64.tar.gz)

So, as you mentioned, requests in your output file for some reason does not contain header section with requests ids and timestamps. It lost somewhere in the middle. Can you check how your kafka raw message looks like, and if it has the metadata?

Thank you!

**Comment by satishmane** [comment]
@buger 

1. I tried latest binary, but same error. Is this because it is expecting meta data for every kafka message. But there is not meta data, it contains only actual data payload as below at the bottom. 

/home/ubuntu/gor --input-kafka-host 'ipaddr:9092' --input-kafka-topic 'kafkatopic' --output-file /home/ubuntu/payload.log --output-file-append

Version: DEV-1519933407
panic: runtime error: index out of range

goroutine 103 [running]:
main.CopyMulty(0x7f660cf3a000, 0xc4212394a0, 0xc4211b8d30, 0x1, 0x1, 0xf2133c000, 0xf)
	/go/src/github.com/buger/goreplay/emitter.go:64 +0xddf
created by main.Start
	/go/src/github.com/buger/goreplay/emitter.go:28 +0xb8

2. The raw kafka message is same as I posted earlier here. It does not have any metadata? It contains exact payload as below.

{"acc":"445","id":"6","md":"ft","cid":"trs","tmud":"6767-ghh","ctype":"application/json","content":{"mid":"6767","mtype":"1","stype":"1","msgtype":"2","seqNo":21080,"utm
":1521833361,"tmfx":1521833361,"lat":9.5961,"lng":106.8297576,"alt":0}}

**Comment by buger** [comment]
Yes, the issue is definitely because of missing headers. 

Can you record some traffic again, but now additionally pass `--output-kafka-json-format`  option to GoReplay both when recording and replaying?

**Comment by satishmane** [comment]
@buger 
I already tried that, but it failed with same error. Since meta data is not there, it fails straightaway. Is goreplay not able to pull meta data from kafka? OR something need to be done on our kafka cluster - I guess not?

gor --input-kafka-host 'IP:9092' --input-kafka-topic 'kafkatopic' --output-file /home/ubuntu/req.log --output-file-append --output-kafka-json-format

Version: DEV-1519933407
panic: runtime error: index out of range

goroutine 100 [running]:
main.CopyMulty(0x7fbf04318e40, 0xc4212274a0, 0xc4211a6d20, 0x1, 0x1, 0xf200101b0, 0xf)
	/go/src/github.com/buger/goreplay/emitter.go:64 +0xddf
created by main.Start
	/go/src/github.com/buger/goreplay/emitter.go:28 +0xb8
