### ISSUE TITLE
I have got this error while trying to run a goreplay 0.16.1 with a custom middleware

### ISSUE THREAD

**Issue by bertolo1988** [buger/goreplay#641]
I am running it inside a docker container with the following command:

```
goreplay --input-raw :80 --input-raw-track-response --middleware "./middleware/middleware.js" --output-http-track-response --output-http http://$MIRROR_HOST --http-set-header "x-mirroring-proxy: true" --prettify-http
```

On my local machine it seems to work but inside a docker container i get:

```
Failed to decode input payload encoding/hex: odd length hex string 21156
panic: runtime error: index out of range

goroutine 37 [running]:
panic(0xa58cc0, 0xc820014040)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
main.CopyMulty(0x7f51781986f0, 0xc820017a40, 0xc821160340, 0x1, 0x1, 0x0, 0x0)
    /go/src/github.com/buger/goreplay/emitter.go:64 +0x1228
created by main.Start
    /go/src/github.com/buger/goreplay/emitter.go:25 +0x2b4
```

What could this be?

**Comment by buger** [comment]
I see that you closed it, was it actually solved?
