### ISSUE TITLE
got the runtime error when i complied gor by myself

### ISSUE THREAD

**Issue by ShaoNianyr** [buger/goreplay#726]
Verison:
Linux Ubuntu 18.04 
libpcap-1.9.1
go-1.13.5

COMPLIE CMD:  go build -ldflags '-X main.VERSION=1.1.0 -extldflags "-static"'

Then I got some warings.

```
# github.com/buger/goreplay
/tmp/go-link-286952507/000004.o：在函数‘_cgo_26061493d47f_C2func_getaddrinfo’中：
/tmp/go-build/cgo-gcc-prolog:58: 警告： Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
//usr/local/lib/libpcap.a(nametoaddr.o)：在函数‘pcap_nametoaddr’中：
/home/shaonian/download/libpcap-1.9.1/./nametoaddr.c:165: 警告： Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
//usr/local/lib/libpcap.a(nametoaddr.o)：在函数‘pcap_nametonetaddr’中：
/home/shaonian/download/libpcap-1.9.1/./nametoaddr.c:249: 警告： Using 'getnetbyname_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
//usr/local/lib/libpcap.a(nametoaddr.o)：在函数‘pcap_nametoproto’中：
/home/shaonian/download/libpcap-1.9.1/./nametoaddr.c:506: 警告： Using 'getprotobyname_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

When I used this goreplay, it could work at the beginnig, and the crash because of runtime errors.

```
1 e13a2d6d144efcdfebabf62a662d9a1bac14c565 1578456223436042579
GET /books HTTP/1.1
Host: localhost:5000
Connection: keep-alive
Accept: application/json, text/plain, */*
Origin: http://localhost:8080
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors
Referer: http://localhost:8080/
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9


fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f43185ec448]

runtime stack:
runtime.throw(0xb45102, 0x2a)
	/usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:378 +0x47c

goroutine 153 [syscall]:
runtime.cgocall(0x8d0f40, 0xc0004e1d60, 0xc000010068)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc0004e1d30 sp=0xc0004e1cf8 pc=0x403efb
net._C2func_getaddrinfo(0xc000540040, 0x0, 0xc0000ee240, 0xc000010068, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:92 +0x55 fp=0xc0004e1d60 sp=0xc0004e1d30 pc=0x5ee125
net.cgoLookupIPCNAME.func1(0xc000540040, 0xa, 0xa, 0xc0000ee240, 0xc000010068, 0x0, 0x0, 0xc0004e1e48)
	/usr/local/go/src/net/cgo_unix.go:161 +0x13e fp=0xc0004e1da8 sp=0xc0004e1d60 pc=0x5f3f1e
net.cgoLookupIPCNAME(0xb1b163, 0x3, 0xc00026e0c7, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/cgo_unix.go:161 +0x191 fp=0xc0004e1f18 sp=0xc0004e1da8 pc=0x5ef691
net.cgoIPLookup(0xc0000ec660, 0xb1b163, 0x3, 0xc00026e0c7, 0x9)
	/usr/local/go/src/net/cgo_unix.go:218 +0x67 fp=0xc0004e1fb8 sp=0xc0004e1f18 pc=0x5efdf7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0004e1fc0 sp=0xc0004e1fb8 pc=0x45fde1
created by net.cgoLookupIP
	/usr/local/go/src/net/cgo_unix.go:228 +0xc7

goroutine 1 [runnable]:
main.Start(0xc00012c300)
	/home/shaonian/go/src/goreplay/emitter.go:55 +0x1be
main.main()
	/home/shaonian/go/src/goreplay/gor.go:104 +0x549

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41
```

Questions:
What's wrong in this process? How to complie?

**Comment by ShaoNianyr** [comment]
These erros might be caused by libcap. If you add goreplay  in an docker image, it  works fine.
