### ISSUE TITLE
[1.2.0] panic: runtime error: slice bounds out of range [13:12]

### ISSUE THREAD

**Issue by cofyc** [buger/goreplay#825]
```
panic: runtime error: slice bounds out of range [13:12]

goroutine 7 [running]:
github.com/buger/goreplay/proto.HasResponseTitle(0xc00027ec66, 0xb7, 0xb7, 0xc002610200)
	/go/src/github.com/buger/goreplay/proto/proto.go:357 +0x242
main.startHint(0xc002c12370, 0xc0003a0630)
	/go/src/github.com/buger/goreplay/input_raw.go:203 +0x7c
github.com/buger/goreplay/tcp.(*MessagePool).Handler(0xc0003a2a40, 0x1124fc0, 0xc003d5da20)
	/go/src/github.com/buger/goreplay/tcp/tcp_message.go:176 +0x9fa
github.com/buger/goreplay/capture.(*Listener).Listen(0xc00034f4a0, 0x1118860, 0xc0003a2a80, 0xc000380400, 0x0, 0x0)
	/go/src/github.com/buger/goreplay/capture/capture.go:163 +0x163
github.com/buger/goreplay/capture.(*Listener).ListenBackground.func1(0xc00011efc0, 0xc00034f4a0, 0x1118860, 0xc0003a2a80, 0xc000380400)
	/go/src/github.com/buger/goreplay/capture/capture.go:173 +0x7b
created by github.com/buger/goreplay/capture.(*Listener).ListenBackground
	/go/src/github.com/buger/goreplay/capture/capture.go:171 +0x84
```

**Comment by urbanishimwe** [comment]
@cofyc care to provide more context

**Comment by cofyc** [comment]
command:

```
./gor --input-raw :80 \
    --input-raw-track-response \
    --output-http-track-response \
    --output-file ok \
    --middleware "bash ./echo.sh" \
    --verbose 1
```

`echo.sh` is the example middleware in https://github.com/buger/goreplay/tree/master/examples/middleware.

gor 1.1.0 works well, but gor 1.2.0 can't in our production environment.

I guess it panics because gor 1.2.0 has bugs in HTTP requests/responses parsing, because the captured requests/responses received by middleware are incomplete.

**Comment by urbanishimwe** [comment]
would you provide the example of the response/request that caused the panic @cofyc

**Comment by cofyc** [comment]
> would you provide the example of the response/request that caused the panic @cofyc
> 
> **EDIT**
> because I can't really reproduce this issue in any way!

I found the bug can't be reproduced from the output file. So I try to modify the goreplay and capture the invalid payload in our production environment, here is an example:

```
2020/09/24 21:21:14 [PPID 16629 and PID 16683] Version:1.2.0
invalid payload: HTTP/1.1 200
Server: Tengine
Content-Length: 0
Connection: close
Access-Control-Allow-Origin: *
Date: Thu, 24 Sep 2020 13:21:19 GMT
x-log-requestid: 5F6C9D4F0E53587D66DA09E5
```
