### ISSUE TITLE
odd length hex string when using middleware

### ISSUE THREAD

**Issue by jonyt** [buger/goreplay#873]
I tried out the node.js, ruby and java examples in the middleware example folders. The node.js one was ok but the other two failed with:

Ruby:
```
[DEBUG][PID 11048][1608203285700342000][0.349500ms] [MIDDLEWARE-MASTER] Starting reading from HTTP output: http://localhost:8080
Failed to decode input payload encoding/hex: odd length hex string 1244
Failed to decode input payload encoding/hex: odd length hex string 1238
Failed to decode input payload encoding/hex: odd length hex string 1244
Failed to decode input payload encoding/hex: odd length hex string 1298
Failed to decode input payload encoding/hex: odd length hex string 1244
Failed to decode input payload encoding/hex: odd length hex string 1238
panic: runtime error: index out of range

goroutine 67 [running]:
main.CopyMulty(0xa63410, 0x13cac1b0, 0x1499c768, 0x1, 0x1, 0x0, 0x4c)
        c:/users/administrator/work/src/github.com/buger/gor/emitter.go:64 +0xa7a
created by main.Start
        c:/users/administrator/work/src/github.com/buger/gor/emitter.go:25 +0x318
```

Java:
```
[DEBUG][PID 14864][1608202717480694100][0.000000ms] [MIDDLEWARE-MASTER] Starting reading from HTTP output: http://localhost:8080
Failed to decode input payload encoding/hex: odd length hex string 1244
panic: runtime error: index out of range

goroutine 57 [running]:
main.CopyMulty(0xa63410, 0x13a401b0, 0x1473c768, 0x1, 0x1, 0x0, 0x4c)
        c:/users/administrator/work/src/github.com/buger/gor/emitter.go:64 +0xa7a
created by main.Start
        c:/users/administrator/work/src/github.com/buger/gor/emitter.go:25 +0x318
```

How can I solve this?

**Comment by urbanishimwe** [comment]
it looks like you are using former versions(1.1-), try using v1.2.0

**Comment by jonyt** [comment]
Is there a compiled version for Windows? I couldn't find one.
