### ISSUE TITLE
Goreplay panic when HTTP chunks are not complete

### ISSUE THREAD

**Issue by davidFR** [buger/goreplay#910]
GoReplay crashes with : 
```
panic: runtime error: slice bounds out of range [549406:549405]

goroutine 18 [running]:
github.com/buger/goreplay/proto.CheckChunked(0xc002fc417d, 0x8621d, 0xb33bb, 0xc000492400)
	/tmp/src/proto/proto.go:431 +0x318
  github.com/buger/goreplay/proto.HasFullPayload(0xc002fc4000, 0x8639a, 0xb3538, 0x11122a0, 0xc00125adc0, 0xc000067d60)
	/tmp/src/proto/proto.go:497 +0x14d
main.http1EndHint(0xc00125adc0, 0xc000161000)
	/tmp/src/input_raw.go:211 +0x74
github.com/buger/goreplay/tcp.(*MessagePool).addPacket(0xc0001d2be0, 0xc00125adc0, 0xc000161000)
	/tmp/src/tcp/tcp_message.go:272 +0x106
github.com/buger/goreplay/tcp.(*MessagePool).Handler(0xc0001d2be0, 0x112a120, 0xc000152160)
	/tmp/src/tcp/tcp_message.go:200 +0x9b3
github.com/buger/goreplay/capture.(*Listener).Listen(0xc0002af130, 0x111db20, 0xc0003705c0, 0xc00018f730, 0x0, 0x0)
	/tmp/src/capture/capture.go:163 +0x163
github.com/buger/goreplay/capture.(*Listener).ListenBackground.func1(0xc000188cc0, 0xc0002af130, 0x111db20, 0xc0003705c0, 0xc00018f730)
	/tmp/src/capture/capture.go:173 +0x7b
created by github.com/buger/goreplay/capture.(*Listener).ListenBackground
	/tmp/src/capture/capture.go:171 +0x84
```

Index is never the same so we don't think it is a raw-buffer-size problem 
```
panic: runtime error: slice bounds out of range [1041406:1041405]
```

Any advice ?

**Comment by urbanishimwe** [comment]
@davidFR is there a way the issue can be reproduced (like data)?

**Comment by davidFR** [comment]
@urbanishimwe I had the following code in proto.CheckChunked : 
```go
func CheckChunked(buf []byte) (chunkEnd int) {
	defer func() {
		if r := recover(); r != nil {
			fmt.Println("Error in CheckChunked:")
			fmt.Println(string(buf))
			chunkEnd = -1
		}
	}()
```

I can't give you all the chunks here, but I can say :
* it is a part of a JSON
* each time it is an incomplete JSON
* all chunks seems OK except the last one

Example : here a buffer of 139404 bytes
```
...99 105 114 99 111 110 13 10 50 48 48 48 13
```
You can see that \10 is missing :
```
...circon\r\n
2000\r
```
GoReplay didn't record LF but in our production, clients (here Java clients) gathered all chunks and receive the complete Json  

Perhaps, it is better to use a recover function in CheckChunked to avoid GoReplay crashes ? 
But what can explain that GoReplay miss a character ?
