### ISSUE TITLE
error occurs while do output or input with Kafka

### ISSUE THREAD

**Issue by caoyunIKEA** [buger/goreplay#911]
_version: 1.2.0 (downloaded from this GitHub repo)
os: MacOS Mojave 10.14.6_

Hi, when I execute the following sample command in the project Wiki:
```
gor --input-raw :8080 --output-kafka-host '192.168.0.1:9092,192.168.0.2:9092' --output-kafka-topic 'kafka-log'
```

this error occurs:
```
panic: reflect: Call with too many input arguments

goroutine 1 [running]:
reflect.Value.call(0x488e500, 0x4a15b60, 0x13, 0x49c1c1e, 0x4, 0xc00018f020, 0x3, 0x4, 0x1, 0x0, ...)
	/usr/local/go/src/reflect/value.go:380 +0x134c
reflect.Value.Call(0x488e500, 0x4a15b60, 0x13, 0xc00018f020, 0x3, 0x4, 0x2, 0x4, 0x1)
	/usr/local/go/src/reflect/value.go:321 +0xb4
main.(*InOutPlugins).registerPlugin(0xc0001d0780, 0x488e500, 0x4a15b60, 0xc00029fda8, 0x3, 0x3)
	/Users/leonidbugaev/go/src/github.com/buger/goreplay/plugins.go:50 +0x1f4
main.NewPlugins(0xc00012a240)
	/Users/leonidbugaev/go/src/github.com/buger/goreplay/plugins.go:140 +0x52f
main.main()
	/Users/leonidbugaev/go/src/github.com/buger/goreplay/gor.go:53 +0x8bc
```

I know it's a sample host and topic name, I also tried the actual ones, but got the same error.  So I guess it's not the command problem

**Comment by caoyunIK** [comment]
I also tried with 1.3.0 RC, it started successfully, however, my kafka broker did not receive any message, command:

```
gor  --input-raw :8080 --output-kafka-host 'localhost:9092,localhost:9093,localhost:9094'  --output-kafka-topic  'test'
```
