### ISSUE TITLE
panic: runtime error: slice bounds out of range [:-2305595756525852402]

### ISSUE THREAD

**Issue by yaowenqiang** [buger/goreplay#968]
panic: runtime error: slice bounds out of range [:-2305595756525852402]

goroutine 5 [running]:
github.com/buger/goreplay/proto.CheckChunked(0xc0026bb189, 0x886, 0xa77, 0xc00005cc11)
	/go/src/github.com/buger/goreplay/proto/proto.go:435 +0x310
github.com/buger/goreplay/proto.HasFullPayload(0xc0026bb000, 0xa0f, 0xc00, 0xc0026bb000)
	/go/src/github.com/buger/goreplay/proto/proto.go:455 +0x17b
main.endHint(0xc0033526e0, 0xc00238db36)
	/go/src/github.com/buger/goreplay/input_raw.go:207 +0x41
github.com/buger/goreplay/tcp.(*MessagePool).addPacket(0xc00027ec80, 0xc0033526e0, 0xc0033603c0)
	/go/src/github.com/buger/goreplay/tcp/tcp_message.go:217 +0x1ee
github.com/buger/goreplay/tcp.(*MessagePool).Handler(0xc00027ec80, 0x1124fc0, 0xc0033a4b00)
	/go/src/github.com/buger/goreplay/tcp/tcp_message.go:171 +0xa84
github.com/buger/goreplay/capture.(*Listener).Listen(0xc000213080, 0x1118860, 0xc00027ecc0, 0xc00003f840, 0x0, 0x0)
	/go/src/github.com/buger/goreplay/capture/capture.go:163 +0x163
github.com/buger/goreplay/capture.(*Listener).ListenBackground.func1(0xc000078f60, 0xc000213080, 0x1118860, 0xc00027ecc0, 0xc00003f840)
	/go/src/github.com/buger/goreplay/capture/capture.go:173 +0x7b
created by github.com/buger/goreplay/capture.(*Listener).ListenBackground
	/go/src/github.com/buger/goreplay/capture/capture.go:171 +0x84

**Comment by buger** [comment]
Thanks! Which GoReplay version?

**Comment by yaowenqiang** [comment]
Version:1.2.0

**Comment by buger** [comment]
Can you try latest 1.3 RC pls? A lot of this code was refactored.

**Comment by yaowenqiang** [comment]
> Can you try latest 1.3 RC pls? A lot of this code was refactored.

Ok, i will have a try

**Comment by yaowenqiang** [comment]
./gor version
./gor flag redefined: cpuprofile
panic: ./gor flag redefined: cpuprofile

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc00011a240, 0x10709c0, 0xc00028b4c0, 0xefee45, 0xa, 0xf177a0, 0x19)
        /usr/local/go/src/flag/flag.go:851 +0x485
flag.(*FlagSet).StringVar(...)
        /usr/local/go/src/flag/flag.go:754
flag.(*FlagSet).String(0xc00011a240, 0xefee45, 0xa, 0x0, 0x0, 0xf177a0, 0x19, 0x0)
        /usr/local/go/src/flag/flag.go:767 +0xa5
flag.String(0xefee45, 0xa, 0x0, 0x0, 0xf177a0, 0x19, 0x0)
        /usr/local/go/src/flag/flag.go:774 +0x69
main.init()
        /go/src/github.com/buger/goreplay/gor.go:21 +0x57

version:  v1.3.0_RC6_x64

**Comment by yaowenqiang** [comment]
I changed to RC5 version the error is gone.

> ./gor version
> ./gor flag redefined: cpuprofile
> panic: ./gor flag redefined: cpuprofile
> 
> goroutine 1 [running]:
> flag.(*FlagSet).Var(0xc00011a240, 0x10709c0, 0xc00028b4c0, 0xefee45, 0xa, 0xf177a0, 0x19)
> /usr/local/go/src/flag/flag.go:851 +0x485
> flag.(*FlagSet).StringVar(...)
> /usr/local/go/src/flag/flag.go:754
> flag.(*FlagSet).String(0xc00011a240, 0xefee45, 0xa, 0x0, 0x0, 0xf177a0, 0x19, 0x0)
> /usr/local/go/src/flag/flag.go:767 +0xa5
> flag.String(0xefee45, 0xa, 0x0, 0x0, 0xf177a0, 0x19, 0x0)
> /usr/local/go/src/flag/flag.go:774 +0x69
> main.init()
> /go/src/github.com/buger/goreplay/gor.go:21 +0x57
> 
> version: v1.3.0_RC6_x64

I changed to RC% version and this error is gone
