### ISSUE TITLE
gor run error

### ISSUE THREAD

**Issue by arrow2012** [buger/goreplay#969]
version : v1.3.0_RC6   CentOS Linux release 7.7.1908

root@server01#gor --help
gor flag redefined: cpuprofile
panic: gor flag redefined: cpuprofile

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0000c0240, 0x10709c0, 0xc0000654f0, 0xefee45, 0xa, 0xf177a0, 0x19)
  /usr/local/go/src/flag/flag.go:851 +0x485
flag.(*FlagSet).StringVar(...)
  /usr/local/go/src/flag/flag.go:754
flag.(*FlagSet).String(0xc0000c0240, 0xefee45, 0xa, 0x0, 0x0, 0xf177a0, 0x19, 0x0)
  /usr/local/go/src/flag/flag.go:767 +0xa5
flag.String(0xefee45, 0xa, 0x0, 0x0, 0xf177a0, 0x19, 0x0)
  /usr/local/go/src/flag/flag.go:774 +0x69
main.init()
  /go/src/github.com/buger/goreplay/gor.go:21 +0x57

**Comment by buger** [comment]
Yes, known issue pls use RC5. 
Final 1.3.0 releasing soon.
