### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by farmage** [buger/goreplay#990]
running as:
```
sudo gor --input-raw :18283 --input-raw-protocol binary --output-binary localhost:18280
```
constantly got the error after few packets processed well

```
goroutine 34 [running]:
github.com/buger/goreplay/tcp.(*MessageParser).processPacket(0xc000190080, 0xc000362dd0)
        /go/src/github.com/buger/goreplay/tcp/tcp_message.go:305 +0xba
github.com/buger/goreplay/tcp.(*MessageParser).wait(0xc000190080)
        /go/src/github.com/buger/goreplay/tcp/tcp_message.go:259 +0x1eb
created by github.com/buger/goreplay/tcp.NewMessageParser
        /go/src/github.com/buger/goreplay/tcp/tcp_message.go:240 +0x194
Interface: eno1 . BPF Filter: ((tcp dst port 18283) and (dst host 5.135.180.196 or dst host 2001:41d0:8:bbc4::1 or dst host fe80::4e72:b9ff:fed1:cb74))
Interface: any . BPF Filter: (tcp dst port 18283)
Interface: lo . BPF Filter: ((tcp dst port 18283) and (dst host 127.0.0.1 or dst host ::1))
Interface: nflog . BPF Filter: (tcp dst port 18283)
Interface: nfqueue . BPF Filter: (tcp dst port 18283)
2021/08/11 11:37:23 [PPID 13577 and PID 13579] Version:1.3.0
2021/08/11 11:37:23 stopped reading from nfqueue interface with error Read Error
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc0f21a]
```

**Comment by buger** [comment]
Version 1.3?

**Comment by farmage** [comment]
yes
Current Version: v1.3.0

**Comment by farmage** [comment]
downloaded from Releases
my host:
Linux ns3289880 4.15.0-147-generic #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by buger** [comment]
Just to clarify, are you using GoReplay PRO version (since binary support is limited to it). Also, which protocol you're trying to catch?

**Comment by farmage** [comment]
I'm using the regular, possible community edition, version from Github releases. 
The protocol is a custom RAW socket communication, Ascii text-based.
I'm expected the GoR will just copy streams without parsing it. Is it possible to use some mode to skip parsing? Maybe it will help
